services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\Framework\Session\PHPSession: ~

  App\Framework\Session\SessionInterface:
    alias: App\Framework\Session\PHPSession

  App\Framework\Session\FlashService:
    arguments:
      $session: '@App\Framework\Session\SessionInterface'

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Pages\:
    resource: '../src/Pages/'
    tags: ['controller.service_arguments']

  App\Pages\Admin\:
    resource: '../src/Pages/Admin'
    tags: ['controller.service_arguments']

  App\controller\:
    resource: "../src/Controller"
    tags: ['controller.service_arguments']

parameters:
    images_directory: '%kernel.project_dir%/public/uploads/images'